spring:
  profiles:
    active: local
  rabbitmq:
      addresses: ${vcap.services.springtrader-cloud-bus-amqp.credentials.uri:amqp://${RABBITMQ_HOST:localhost}:${RABBITMQ_PORT:5672}}

security:
  basic:
    enabled: false



expiration:
  time: -1 # enable offline mode. no expiration.

---
spring:
  profiles: local

server:
  port: 8086

security:
  basic:
    enabled: false
---
spring:
  profiles: cloud
---
api:
 url:
   company: http://dev.markitondemand.com/MODApis/Api/v2/Lookup/json?input={name}
   quote: http://dev.markitondemand.com/MODApis/Api/v2/Quote/json?symbol={symbol}
